[package]
name = "plugin-wasi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "component:plugin-wasi"

[package.metadata.component.dependencies]

[dependencies]
wit-bindgen = { version = "0.15.0" }
rand = "*"
