version: "3.7"

services:
  bevy-test-wasmer:
    image: nginx:latest
    container_name: bevy-test-wasmer
    ports:
      - "8089:80"
    volumes:
      - .:/usr/share/nginx/html
    restart: unless-stopped
