package component:guest-reactor;

/// An example world for the component to target.
world example {
    record vector {
        x: s32,
        y: s32,
        z: s32,
    }
   
    import import-vector-round: func(v: vector) -> vector;
    export export-vector-round: func(v: vector) -> vector;

    import import-vector-list: func(l: list<vector>) -> list<vector>;
    export export-vector-list: func(l: list<vector>) -> list<vector>;

    import import-s32: func(s: s32) -> s32;
    export export-s32: func(s: s32) -> s32;

    import import-string: func(s: string) -> string;
    export export-string: func(s: string) -> string;

    import import-insane: func(i: tuple<vector, vector, vector, vector, vector, vector>) -> tuple<vector, vector, vector, vector, vector, vector>;
    export export-insane: func(i: tuple<vector, vector, vector, vector, vector, vector>) -> tuple<vector, vector, vector, vector, vector, vector>;
    
}
