package example:protocol;

interface companies {
  resource company {
    constructor(name: string, max-salary: u32);
    get-name: func() -> string;
    get-max-salary: func() -> u32;
  }
}

interface employees {
  resource employee {
    constructor(name: string, min-salary: u32);
    get-name: func() -> string;
    get-min-salary: func() -> u32;
  }
}

world my-world {
  use companies.{company};
  use employees.{employee};

  import companies;
  export employees;

  import can-employee-work-at: func(employee: borrow<employee>, company: borrow<company>) -> bool;
  export find-job: func(employee: borrow<employee>, companies: list<company>) -> option<company>;
}
