[package]
name = "guest-rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen = { version = "0.15.0" }

[package.metadata.component]
package = "component:guest-rust"

[package.metadata.component.dependencies]
