[package]
name = "bevy-web-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.10.0"
wai-bindgen-wasmer = { version = "0.2.4", features = ["js"] }
